// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFWebservice;

#nullable disable

namespace SFWebservice.Migrations
{
    [DbContext(typeof(Sfdb01Context))]
    [Migration("20260107123550_Change-Hit")]
    partial class ChangeHit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SFWebservice.Modules.Dodge", b =>
                {
                    b.Property<int>("DodgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DodgeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DodgeId"));

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("int")
                        .HasColumnName("GameSessionID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DodgeId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Dodge", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.GameSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameSession", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.Hit", b =>
                {
                    b.Property<int>("HitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HitId"));

                    b.Property<bool>("EntityHitId")
                        .HasColumnType("bit")
                        .HasColumnName("EntityHitID");

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("int")
                        .HasColumnName("GameSessionID");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("HitId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Hit", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.Objective", b =>
                {
                    b.Property<int>("ObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObjectiveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectiveId"));

                    b.Property<string>("ObjectiveName")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.HasKey("ObjectiveId");

                    b.ToTable("Objective", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.ObjectiveCompleted", b =>
                {
                    b.Property<int>("ObjectiveCompletedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObjectiveCompletedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectiveCompletedId"));

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("int")
                        .HasColumnName("GameSessionID");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeCompleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectiveCompletedId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("ObjectiveCompleted", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("SFWebservice.Modules.Dodge", b =>
                {
                    b.HasOne("SFWebservice.Modules.GameSession", "GameSession")
                        .WithMany("Dodges")
                        .HasForeignKey("GameSessionId")
                        .HasConstraintName("FK_Dodge_GameSession");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("SFWebservice.Modules.GameSession", b =>
                {
                    b.HasOne("SFWebservice.Modules.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_GameSession_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SFWebservice.Modules.Hit", b =>
                {
                    b.HasOne("SFWebservice.Modules.GameSession", "GameSession")
                        .WithMany("Hits")
                        .HasForeignKey("GameSessionId")
                        .HasConstraintName("FK_Hit_GameSession");

                    b.HasOne("SFWebservice.Modules.Player", null)
                        .WithMany("Hits")
                        .HasForeignKey("PlayerId");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("SFWebservice.Modules.ObjectiveCompleted", b =>
                {
                    b.HasOne("SFWebservice.Modules.GameSession", "GameSession")
                        .WithMany("ObjectiveCompleteds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ObjectiveCompleted_GameSession");

                    b.HasOne("SFWebservice.Modules.Objective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId");

                    b.Navigation("GameSession");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("SFWebservice.Modules.GameSession", b =>
                {
                    b.Navigation("Dodges");

                    b.Navigation("Hits");

                    b.Navigation("ObjectiveCompleteds");
                });

            modelBuilder.Entity("SFWebservice.Modules.Player", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Hits");
                });
#pragma warning restore 612, 618
        }
    }
}
